// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;
using YiJian.Nursing.EntityFrameworkCore;

namespace YiJian.Nursing.Migrations
{
    [DbContext(typeof(NursingHttpApiHostMigrationsDbContext))]
    [Migration("20211014061858_Update_IllnessObserveMain_1014")]
    partial class Update_IllnessObserveMain_1014
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YiJian.Nursing.IllnessObserveHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<int>("Grade")
                        .HasColumnType("int")
                        .HasComment("等级，1:一级，2：二级");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasComment("项目编码");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasComment("项目名称");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LastModifierId");

                    b.Property<decimal>("MaxEarlyWarning")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("最大值预警");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("最大值");

                    b.Property<decimal>("MinEarlyWarning")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("最小值预警");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("最小值");

                    b.Property<string>("ParentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasComment("父级编码");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(50)")
                        .HasComment("单位");

                    b.HasKey("Id");

                    b.ToTable("NursingIllnessObserveHeader");

                    b
                        .HasComment("病情观察头部");
                });

            modelBuilder.Entity("YiJian.Nursing.IllnessObserveInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BloodTransfusion")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("输血");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("Diet")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("饮食");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<Guid>("IllnessObserveMainId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("主表id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("NasalFeeding")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("鼻饲");

                    b.Property<string>("TotalInput")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("入量合计");

                    b.Property<string>("Water")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("水");

                    b.HasKey("Id");

                    b.HasIndex("IllnessObserveMainId")
                        .IsUnique();

                    b.ToTable("NursingIllnessObserveInput");

                    b
                        .HasComment("病情观察入量表");
                });

            modelBuilder.Entity("YiJian.Nursing.IllnessObserveMain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BloodSugar")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("血糖");

                    b.Property<string>("Breathing")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("呼吸");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("ConsciousnessCode")
                        .HasColumnType("nvarchar(50)")
                        .HasComment("意识编码");

                    b.Property<string>("ConsciousnessName")
                        .HasColumnType("nvarchar(100)")
                        .HasComment("意识名称");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("HeartRate")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("心率");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("LeftPupilSize")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("左瞳大小");

                    b.Property<int>("LeftPupilType")
                        .HasColumnType("int")
                        .HasComment("左瞳类型，0：灵敏，1：迟钝，2：无反应");

                    b.Property<string>("ObserveTime")
                        .HasColumnType("nvarchar(20)")
                        .HasComment("时间");

                    b.Property<Guid>("PI_ID")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("traige患者id");

                    b.Property<string>("PatientId")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("患者id");

                    b.Property<string>("RightPupilSize")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("右瞳大小");

                    b.Property<int>("RightPupilType")
                        .HasColumnType("int")
                        .HasComment("右瞳类型，0：灵敏，1：迟钝，2：无反应");

                    b.Property<string>("Sbp")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("血压BP收缩压");

                    b.Property<string>("Sdp")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("血压BP舒张压");

                    b.Property<string>("SpO2")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("血氧饱和度");

                    b.Property<string>("Temperature")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("体温");

                    b.Property<string>("VisitNo")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("就诊号");

                    b.HasKey("Id");

                    b.ToTable("NursingIllnessObserveMain");

                    b
                        .HasComment("病情观察");
                });

            modelBuilder.Entity("YiJian.Nursing.IllnessObserveOther", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("C")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("GCS分");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("ElectricCardioversion")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("电复律");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("G")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("GCS分");

                    b.Property<Guid>("IllnessObserveMainId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("主表id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("S")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("GCS分");

                    b.Property<string>("TurnOver")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("翻身");

                    b.HasKey("Id");

                    b.HasIndex("IllnessObserveMainId")
                        .IsUnique();

                    b.ToTable("NursingIllnessObserveOther");

                    b
                        .HasComment("病情观察其他");
                });

            modelBuilder.Entity("YiJian.Nursing.IllnessObserveOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("ExtraProperties")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<Guid>("IllnessObserveMainId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("主表id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Shit")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("大便");

                    b.Property<string>("SputumSuction")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("吸痰");

                    b.Property<string>("Sweat")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("汗液");

                    b.Property<string>("TotalOutput")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("出量合计");

                    b.Property<string>("UrineVolume")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("尿量");

                    b.Property<string>("VenousInflow")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("静脉入量");

                    b.Property<string>("Vomit")
                        .HasColumnType("nvarchar(10)")
                        .HasComment("呕吐");

                    b.HasKey("Id");

                    b.HasIndex("IllnessObserveMainId")
                        .IsUnique();

                    b.ToTable("NursingIllnessObserveOutput");

                    b
                        .HasComment("病情观察出量表");
                });

            modelBuilder.Entity("YiJian.Nursing.IllnessObserveInput", b =>
                {
                    b.HasOne("YiJian.Nursing.IllnessObserveMain", null)
                        .WithOne("IllnessObserveInput")
                        .HasForeignKey("YiJian.Nursing.IllnessObserveInput", "IllnessObserveMainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YiJian.Nursing.IllnessObserveOther", b =>
                {
                    b.HasOne("YiJian.Nursing.IllnessObserveMain", null)
                        .WithOne("IllnessObserveOther")
                        .HasForeignKey("YiJian.Nursing.IllnessObserveOther", "IllnessObserveMainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YiJian.Nursing.IllnessObserveOutput", b =>
                {
                    b.HasOne("YiJian.Nursing.IllnessObserveMain", null)
                        .WithOne("IllnessObserveOutput")
                        .HasForeignKey("YiJian.Nursing.IllnessObserveOutput", "IllnessObserveMainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YiJian.Nursing.IllnessObserveMain", b =>
                {
                    b.Navigation("IllnessObserveInput");

                    b.Navigation("IllnessObserveOther");

                    b.Navigation("IllnessObserveOutput");
                });
#pragma warning restore 612, 618
        }
    }
}
